SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

USE riimages;

-- --------------------------------------------------------

--
-- Dumping data for table `riimages.restaurant`
--
INSERT INTO riimages.restaurant(RESTAURANT_ID,RESTAURANT_NAME,RESTAURANT_ADDRESS,SALES,LOGIN_NAME,LOGIN_PASSWORD) VALUES (1,'潇湘四伙计','龙岗区飞扬路启迪协信路8栋130',1287,'XXSHJ',123456789);
INSERT INTO riimages.restaurant(RESTAURANT_ID,RESTAURANT_NAME,RESTAURANT_ADDRESS,SALES,LOGIN_NAME,LOGIN_PASSWORD) VALUES (2,'绿茶','龙岗区中心城龙翔大道7188号万科广场4层',8421,'LC',123456789);
INSERT INTO riimages.restaurant(RESTAURANT_ID,RESTAURANT_NAME,RESTAURANT_ADDRESS,SALES,LOGIN_NAME,LOGIN_PASSWORD) VALUES (3,'吴莊','龙岗区爱南路652号cocopark3层',2333,'WZ',123456789);
INSERT INTO riimages.restaurant(RESTAURANT_ID,RESTAURANT_NAME,RESTAURANT_ADDRESS,SALES,LOGIN_NAME,LOGIN_PASSWORD) VALUES (4,'纳瓦新疆音乐餐厅（天安云谷店）','龙岗区岗辉路天安云谷二期4栋306单元店铺',1406,'NWXJYYCT',123456789);
INSERT INTO riimages.restaurant(RESTAURANT_ID,RESTAURANT_NAME,RESTAURANT_ADDRESS,SALES,LOGIN_NAME,LOGIN_PASSWORD) VALUES (5,'宴兰亭（天安云谷店）','龙岗区环城路天安云谷一期3栋D座二楼210',3141,'YLT',123456789);
--
-- Dumping data for table `riimages.food`
--
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (1,1,'荤菜','辣椒炒肉',42,82);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (2,1,'荤菜','小炒黄牛肉',68,87);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (3,1,'荤菜','剁椒鱼头',96,92);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (4,1,'荤菜','口味鸡',88,54);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (5,1,'荤菜','烟笋炒腊肉',48,44);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (6,1,'素菜','有机花菜',36,70);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (7,1,'素菜','煎茄子',32,51);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (8,1,'素菜','玉米淮山',38,79);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (9,1,'汤','茶树菇土鸡汤',56,106);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (10,1,'汤','筒骨煨湖藕',52,64);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (11,2,'荤菜','葱香烤鸡',35,94);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (12,2,'荤菜','酱爆石锅蛙',58,91);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (13,2,'荤菜','卤制烤鸭',45,49);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (14,2,'荤菜','粉丝裹虾',49,101);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (15,2,'荤菜','盐菜扣肉',38,74);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (16,2,'荤菜','鲜花椒鲈鱼',56,92);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (17,2,'素菜','香锅卷心菜',25,104);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (18,2,'素菜','油淋菜心',18,110);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (19,2,'素菜','香锅花菜',28,75);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (20,2,'汤','石锅鸡汤豆腐',32,64);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (21,3,'荤菜','果木烤鸭',158,42);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (22,3,'荤菜','糖醋里脊',33,101);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (23,3,'荤菜','叫花鸡',48,48);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (24,3,'荤菜','毛血旺',49,110);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (25,3,'荤菜','香锅牛杂',69,92);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (26,3,'素菜','粉丝包菜',27,92);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (27,3,'素菜','香锅土豆片',27,66);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (28,3,'素菜','腐竹鸡毛菜',28,69);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (29,3,'汤','鸭汤',23,92);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (30,3,'汤','鸽子汤',20,60);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (31,4,'主菜','摩登大盘鸡',118,45);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (32,4,'主菜','八柯招牌焖烤羊排',129,49);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (33,4,'主菜','铁板孜然牛肉',62,55);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (34,4,'主菜','草原菇焖大虾',69,81);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (35,4,'凉菜','乌市巷子凉皮',29,91);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (36,4,'凉菜','巴依老爷大拌菜',38,50);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (37,4,'时蔬','包包菜炒馕',28,88);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (38,4,'时蔬','炝炒鸡毛菜',32,63);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (39,4,'小食','纳瓦羊肉水饺',36,99);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (40,4,'汤品','伊犁羊杂汤',58,55);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (41,5,'主菜','茉莉茶香基围虾',82,93);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (42,5,'主菜','草堂文火东坡鸡',105,119);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (43,5,'主菜','兰亭果木烤鸭',98,55);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (44,5,'主菜','火腿淡菜焗黄鱼',105,88);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (45,5,'主菜','小炒黄牛肉',82,41);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (46,5,'主菜','鉴湖什锦全家福',77,73);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (47,5,'小食','灌汤小笼包',26,58);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (48,5,'小食','松子山药泥',19,50);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (49,5,'小食','小米桂花糕',42,113);
INSERT INTO riimages.food(FOOD_ID,RESTAURANT_ID,FOOD_TYPE,FOOD_NAME,PRICE,INVENTORY) VALUES (50,5,'饮品','香蕉牛奶',58,55);
--
-- Dumping data for table `riimages.food`
--




-- --------------------------------------------------------

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;